apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: csharp-weatherforecast
  annotations:
    local-source-proxy.apps.tanzu.vmware.com: us-east1-docker.pkg.dev/tap-sandbox-dev/tapv2-quick-guanaco/lsp:apps-csharp-weatherforecast@sha256:289428fea57960c6992893be1d92c9d4d966927a3ab0f9d89e8a26a41d9a609b
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: csharp-weatherforecast
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    tanzu.app.live.view: "true"
    tanzu.app.live.view.application.flavours: steeltoe
    tanzu.app.live.view.application.name: csharp-weatherforecast
    app.kubernetes.io/component: run
    carto.run/workload-name: csharp-weatherforecast
spec:
  type: openapi
  description: Manage customer profiles
  system: profile-management
  owner: customer-relations-department
  location:
    apiSpec:
      path: /swagger/v1/swagger.json
    server:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: csharp-weatherforecast

